<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6x6jTjg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6x6jTjg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6x6jTjg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6x6jTjg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6x6jTjg\App_KernelDevDebugContainer([
    'container.build_hash' => '6x6jTjg',
    'container.build_id' => 'cff2be92',
    'container.build_time' => 1655021673,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6x6jTjg');
