version: '3'

networks:
    nginx-php74-node-kit:

services:

    # nginx
    nginx-service-kit:
        image: nginx:stable-alpine
        container_name: nginx-container-kit
        ports:
            - "8081:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service-kit
            - mysql8-service-kit
        networks:
            - nginx-php74-node-kit

    # php
    php74-service-kit:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container-kit
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
            - ./php/conf/php.ini:/conf/php.ini:cached
        networks:
            - nginx-php74-node-kit

    # mysql
    mysql8-service-kit:
        image: mysql:8
        container_name: mysql8-container-kit
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - nginx-php74-node-kit
