<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4MduxTService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.h4MduxT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h4MduxT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'unit' => ['privates', '.errored..service_locator.h4MduxT.App\\Entity\\Unit', NULL, 'Cannot autowire service ".service_locator.h4MduxT": it references class "App\\Entity\\Unit" but no such service exists.'],
        ], [
            'translator' => '?',
            'unit' => 'App\\Entity\\Unit',
        ]);
    }
}
