<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4l22a4Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.h4l22a4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h4l22a4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'materialNormReplacement' => ['privates', '.errored..service_locator.h4l22a4.App\\Entity\\MaterialNormReplacement', NULL, 'Cannot autowire service ".service_locator.h4l22a4": it references class "App\\Entity\\MaterialNormReplacement" but no such service exists.'],
            'normDocument' => ['privates', '.errored..service_locator.h4l22a4.App\\Entity\\NormDocument', NULL, 'Cannot autowire service ".service_locator.h4l22a4": it references class "App\\Entity\\NormDocument" but no such service exists.'],
        ], [
            'materialNormReplacement' => 'App\\Entity\\MaterialNormReplacement',
            'normDocument' => 'App\\Entity\\NormDocument',
        ]);
    }
}
