<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Um5BQ0rService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.um5BQ0r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.um5BQ0r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'productionPlan' => ['privates', '.errored..service_locator.um5BQ0r.App\\Entity\\ProductionPlan', NULL, 'Cannot autowire service ".service_locator.um5BQ0r": it references class "App\\Entity\\ProductionPlan" but no such service exists.'],
        ], [
            'productionPlan' => 'App\\Entity\\ProductionPlan',
        ]);
    }
}
