<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JnfAuraService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.jnfAura' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jnfAura'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trackDocument' => ['privates', '.errored..service_locator.jnfAura.App\\Entity\\TrackDocument', NULL, 'Cannot autowire service ".service_locator.jnfAura": it references class "App\\Entity\\TrackDocument" but no such service exists.'],
        ], [
            'trackDocument' => 'App\\Entity\\TrackDocument',
        ]);
    }
}
