<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FWw8bfmService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.FWw8bfm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FWw8bfm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'specificationSection' => ['privates', '.errored..service_locator.FWw8bfm.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.FWw8bfm": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'specificationSection' => 'App\\Entity\\Product',
        ]);
    }
}
