<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L7VuipService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator._L7Vuip' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._L7Vuip'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product_type' => ['privates', '.errored..service_locator._L7Vuip.App\\Entity\\ProductType', NULL, 'Cannot autowire service ".service_locator._L7Vuip": it references class "App\\Entity\\ProductType" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'product_type' => 'App\\Entity\\ProductType',
            'translator' => '?',
        ]);
    }
}
