<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XLJWqnbService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.xLJWqnb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xLJWqnb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rendition' => ['privates', '.errored..service_locator.xLJWqnb.App\\Entity\\Rendition', NULL, 'Cannot autowire service ".service_locator.xLJWqnb": it references class "App\\Entity\\Rendition" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'rendition' => 'App\\Entity\\Rendition',
            'translator' => '?',
        ]);
    }
}
