<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyticGroupService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.gT5hl2d.App\Entity\AnalyticGroup' shared service.
     *
     * @return \App\Entity\AnalyticGroup
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gT5hl2d": it references class "App\\Entity\\AnalyticGroup" but no such service exists.');
    }
}
