<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartmentService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.s8fCHH7.App\Entity\Department' shared service.
     *
     * @return \App\Entity\Department
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.s8fCHH7": it references class "App\\Entity\\Department" but no such service exists.');
    }
}
