<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosJsRouting_RouterDebugExposedCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'fos_js_routing.router_debug_exposed_command' shared service.
     *
     * @return \FOS\JsRoutingBundle\Command\RouterDebugExposedCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['fos_js_routing.router_debug_exposed_command'] = $instance = new \FOS\JsRoutingBundle\Command\RouterDebugExposedCommand(($container->services['fos_js_routing.extractor'] ?? $container->load('getFosJsRouting_ExtractorService')), ($container->services['router'] ?? $container->getRouterService()));

        $instance->setName('fos:js-routing:debug');

        return $instance;
    }
}
