<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceGroupTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\FinanceGroupType' shared autowired service.
     *
     * @return \App\Form\FinanceGroupType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FinanceGroupType'] = new \App\Form\FinanceGroupType();
    }
}
