<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductKindService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.fmkTbCs.App\Entity\ProductKind' shared service.
     *
     * @return \App\Entity\ProductKind
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.fmkTbCs": it references class "App\\Entity\\ProductKind" but no such service exists.');
    }
}
