<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductListenerService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Listener\ProductListener' shared autowired service.
     *
     * @return \App\Listener\ProductListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Listener\\ProductListener'] = new \App\Listener\ProductListener(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), new \Symfony\Component\Security\Core\Security(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'security.authorization_checker' => '?',
            'security.token_storage' => '?',
        ])));
    }
}
