<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductionPlanControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ProductionPlanController' shared autowired service.
     *
     * @return \App\Controller\ProductionPlanController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['App\\Controller\\ProductionPlanController'] = $instance = new \App\Controller\ProductionPlanController($a, ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ProductionPlanController', $container));
        $instance->setEntityManager($a);

        return $instance;
    }
}
