<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCategoryService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.C8oo_nT.App\Entity\ProductCategory' shared service.
     *
     * @return \App\Entity\ProductCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.C8oo_nT": it references class "App\\Entity\\ProductCategory" but no such service exists.');
    }
}
