<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenditionControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\RenditionController' shared autowired service.
     *
     * @return \App\Controller\RenditionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RenditionController'] = $instance = new \App\Controller\RenditionController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\RenditionController', $container));

        return $instance;
    }
}
