<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureReplacementService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator._w2xpoD.App\Entity\StructureReplacement' shared service.
     *
     * @return \App\Entity\StructureReplacement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._w2xpoD": it references class "App\\Entity\\StructureReplacement" but no such service exists.');
    }
}
