<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStructureMaterialTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\StructureMaterialType' shared autowired service.
     *
     * @return \App\Form\StructureMaterialType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\StructureMaterialType'] = new \App\Form\StructureMaterialType(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
