<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificationTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\SpecificationType' shared autowired service.
     *
     * @return \App\Form\SpecificationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\SpecificationType'] = new \App\Form\SpecificationType(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
