<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTechnologicalOperationService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.46WBdVj.App\Entity\TechnologicalOperation' shared service.
     *
     * @return \App\Entity\TechnologicalOperation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.46WBdVj": it references class "App\\Entity\\TechnologicalOperation" but no such service exists.');
    }
}
