<?php

namespace ContainerHYrt1D7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackDocument2Service extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.jnfAura.App\Entity\TrackDocument' shared service.
     *
     * @return \App\Entity\TrackDocument
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jnfAura": it references class "App\\Entity\\TrackDocument" but no such service exists.');
    }
}
