<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GcN_YbSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GcN.ybS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GcN.ybS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'specification' => ['privates', '.errored..service_locator.GcN.ybS.App\\Entity\\Specification', NULL, 'Cannot autowire service ".service_locator.GcN.ybS": it references class "App\\Entity\\Specification" but no such service exists.'],
            'structure' => ['privates', '.errored..service_locator.GcN.ybS.App\\Entity\\Structure', NULL, 'Cannot autowire service ".service_locator.GcN.ybS": it references class "App\\Entity\\Structure" but no such service exists.'],
        ], [
            'specification' => 'App\\Entity\\Specification',
            'structure' => 'App\\Entity\\Structure',
        ]);
    }
}
