<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LZPsTHvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lZPsTHv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lZPsTHv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'materialNorm' => ['privates', '.errored..service_locator.lZPsTHv.App\\Entity\\MaterialNorm', NULL, 'Cannot autowire service ".service_locator.lZPsTHv": it references class "App\\Entity\\MaterialNorm" but no such service exists.'],
            'normDocument' => ['privates', '.errored..service_locator.lZPsTHv.App\\Entity\\NormDocument', NULL, 'Cannot autowire service ".service_locator.lZPsTHv": it references class "App\\Entity\\NormDocument" but no such service exists.'],
        ], [
            'materialNorm' => 'App\\Entity\\MaterialNorm',
            'normDocument' => 'App\\Entity\\NormDocument',
        ]);
    }
}
