<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JV5Q7hJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jV5Q7hJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jV5Q7hJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'analyticGroup' => ['privates', '.errored..service_locator.jV5Q7hJ.App\\Entity\\AnalyticGroup', NULL, 'Cannot autowire service ".service_locator.jV5Q7hJ": it references class "App\\Entity\\AnalyticGroup" but no such service exists.'],
        ], [
            'analyticGroup' => 'App\\Entity\\AnalyticGroup',
        ]);
    }
}
