<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FmkTbCsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fmkTbCs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fmkTbCs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product_kind' => ['privates', '.errored..service_locator.fmkTbCs.App\\Entity\\ProductKind', NULL, 'Cannot autowire service ".service_locator.fmkTbCs": it references class "App\\Entity\\ProductKind" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'product_kind' => 'App\\Entity\\ProductKind',
            'translator' => '?',
        ]);
    }
}
