<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GT5hl2dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gT5hl2d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gT5hl2d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'analyticGroup' => ['privates', '.errored..service_locator.gT5hl2d.App\\Entity\\AnalyticGroup', NULL, 'Cannot autowire service ".service_locator.gT5hl2d": it references class "App\\Entity\\AnalyticGroup" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'analyticGroup' => 'App\\Entity\\AnalyticGroup',
            'translator' => '?',
        ]);
    }
}
