<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8fCHH7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s8fCHH7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s8fCHH7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'department' => ['privates', '.errored..service_locator.s8fCHH7.App\\Entity\\Department', NULL, 'Cannot autowire service ".service_locator.s8fCHH7": it references class "App\\Entity\\Department" but no such service exists.'],
        ], [
            'department' => 'App\\Entity\\Department',
        ]);
    }
}
