<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ERzb3cfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eRzb3cf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eRzb3cf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'normDocument' => ['privates', '.errored..service_locator.eRzb3cf.App\\Entity\\NormDocument', NULL, 'Cannot autowire service ".service_locator.eRzb3cf": it references class "App\\Entity\\NormDocument" but no such service exists.'],
        ], [
            'normDocument' => 'App\\Entity\\NormDocument',
        ]);
    }
}
