<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V5xvyztService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V5xvyzt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V5xvyzt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'specification' => ['privates', '.errored..service_locator.V5xvyzt.App\\Entity\\Specification', NULL, 'Cannot autowire service ".service_locator.V5xvyzt": it references class "App\\Entity\\Specification" but no such service exists.'],
        ], [
            'specification' => 'App\\Entity\\Specification',
        ]);
    }
}
