<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xa5otZ3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xa5otZ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xa5otZ3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'financeGroup' => ['privates', '.errored..service_locator.Xa5otZ3.App\\Entity\\FinanceGroup', NULL, 'Cannot autowire service ".service_locator.Xa5otZ3": it references class "App\\Entity\\FinanceGroup" but no such service exists.'],
        ], [
            'financeGroup' => 'App\\Entity\\FinanceGroup',
        ]);
    }
}
