<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1vkshZKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1vkshZK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1vkshZK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'track' => ['privates', '.errored..service_locator.1vkshZK.App\\Entity\\Track', NULL, 'Cannot autowire service ".service_locator.1vkshZK": it references class "App\\Entity\\Track" but no such service exists.'],
            'trackDocument' => ['privates', '.errored..service_locator.1vkshZK.App\\Entity\\TrackDocument', NULL, 'Cannot autowire service ".service_locator.1vkshZK": it references class "App\\Entity\\TrackDocument" but no such service exists.'],
        ], [
            'track' => 'App\\Entity\\Track',
            'trackDocument' => 'App\\Entity\\TrackDocument',
        ]);
    }
}
