<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9NEpv0YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9NEpv0Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9NEpv0Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'financeGroup' => ['privates', '.errored..service_locator.9NEpv0Y.App\\Entity\\FinanceGroup', NULL, 'Cannot autowire service ".service_locator.9NEpv0Y": it references class "App\\Entity\\FinanceGroup" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'financeGroup' => 'App\\Entity\\FinanceGroup',
            'translator' => '?',
        ]);
    }
}
