<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0jofhNxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0jofhNx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0jofhNx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product_group' => ['privates', '.errored..service_locator.0jofhNx.App\\Entity\\ProductGroup', NULL, 'Cannot autowire service ".service_locator.0jofhNx": it references class "App\\Entity\\ProductGroup" but no such service exists.'],
        ], [
            'product_group' => 'App\\Entity\\ProductGroup',
        ]);
    }
}
