<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_46WBdVjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.46WBdVj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.46WBdVj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'technologicalOperation' => ['privates', '.errored..service_locator.46WBdVj.App\\Entity\\TechnologicalOperation', NULL, 'Cannot autowire service ".service_locator.46WBdVj": it references class "App\\Entity\\TechnologicalOperation" but no such service exists.'],
        ], [
            'technologicalOperation' => 'App\\Entity\\TechnologicalOperation',
        ]);
    }
}
