<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteMaterialNormEmptyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DeleteMaterialNormEmptyCommand' shared autowired service.
     *
     * @return \App\Command\DeleteMaterialNormEmptyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DeleteMaterialNormEmptyCommand.php';

        $container->privates['App\\Command\\DeleteMaterialNormEmptyCommand'] = $instance = new \App\Command\DeleteMaterialNormEmptyCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->privates['App\\Repository\\UnitRepository'] ?? $container->load('getUnitRepositoryService')), ($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')), ($container->privates['App\\Repository\\NormDocumentRepository'] ?? $container->load('getNormDocumentRepositoryService')), ($container->privates['App\\Repository\\RenditionRepository'] ?? $container->load('getRenditionRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\MaterialNormRepository'] ?? $container->load('getMaterialNormRepositoryService')));

        $instance->setName('app:delete:material-norm-empty');

        return $instance;
    }
}
