<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportOperationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ExportOperationCommand' shared autowired service.
     *
     * @return \App\Command\ExportOperationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ExportOperationCommand.php';

        $container->privates['App\\Command\\ExportOperationCommand'] = $instance = new \App\Command\ExportOperationCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setName('app:export:operation');

        return $instance;
    }
}
