<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFinanceGroupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9NEpv0Y.App\Entity\FinanceGroup' shared service.
     *
     * @return \App\Entity\FinanceGroup
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9NEpv0Y": it references class "App\\Entity\\FinanceGroup" but no such service exists.');
    }
}
