<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNormDocumentTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NormDocumentType' shared autowired service.
     *
     * @return \App\Form\NormDocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NormDocumentType.php';

        return $container->privates['App\\Form\\NormDocumentType'] = new \App\Form\NormDocumentType(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
