<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNormDocument3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h4l22a4.App\Entity\NormDocument' shared service.
     *
     * @return \App\Entity\NormDocument
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h4l22a4": it references class "App\\Entity\\NormDocument" but no such service exists.');
    }
}
