<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductKind2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n6xY4Tu.App\Entity\ProductKind' shared service.
     *
     * @return \App\Entity\ProductKind
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.n6xY4Tu": it references class "App\\Entity\\ProductKind" but no such service exists.');
    }
}
