<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductTypeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProductTypeType' shared autowired service.
     *
     * @return \App\Form\ProductTypeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProductTypeType.php';

        return $container->privates['App\\Form\\ProductTypeType'] = new \App\Form\ProductTypeType();
    }
}
