<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductKindControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProductKindController' shared autowired service.
     *
     * @return \App\Controller\ProductKindController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProductKindController.php';

        $container->services['App\\Controller\\ProductKindController'] = $instance = new \App\Controller\ProductKindController(($container->services['translator'] ?? $container->getTranslatorService()));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\ProductKindController', $container));

        return $instance;
    }
}
