<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductionPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.um5BQ0r.App\Entity\ProductionPlan' shared service.
     *
     * @return \App\Entity\ProductionPlan
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.um5BQ0r": it references class "App\\Entity\\ProductionPlan" but no such service exists.');
    }
}
