<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductType2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jA.3S5I.App\Entity\ProductType' shared service.
     *
     * @return \App\Entity\ProductType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jA.3S5I": it references class "App\\Entity\\ProductType" but no such service exists.');
    }
}
