<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductGroupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..bKtgG4.App\Entity\ProductGroup' shared service.
     *
     * @return \App\Entity\ProductGroup
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..bKtgG4": it references class "App\\Entity\\ProductGroup" but no such service exists.');
    }
}
