<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenditionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QUE1fNB.App\Entity\Rendition' shared service.
     *
     * @return \App\Entity\Rendition
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QUE1fNB": it references class "App\\Entity\\Rendition" but no such service exists.');
    }
}
