<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpecificationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SpecificationController' shared autowired service.
     *
     * @return \App\Controller\SpecificationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SpecificationController.php';

        $container->services['App\\Controller\\SpecificationController'] = $instance = new \App\Controller\SpecificationController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->privates['App\\Services\\StructureService'] ?? $container->load('getStructureServiceService')), ($container->privates['App\\Repository\\SpecificationRepository'] ?? $container->load('getSpecificationRepositoryService')), ($container->privates['App\\Repository\\StructureRepository'] ?? $container->load('getStructureRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SpecificationController', $container));

        return $instance;
    }
}
