<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TrackController' shared autowired service.
     *
     * @return \App\Controller\TrackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TrackController.php';
        include_once \dirname(__DIR__, 4).'/src/Services/TrackService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['App\\Controller\\TrackController'] = $instance = new \App\Controller\TrackController($a, ($container->services['translator'] ?? $container->getTranslatorService()), new \App\Services\TrackService($a, ($container->services['twig'] ?? $container->getTwigService()), ($container->services['router'] ?? $container->getRouterService())), ($container->privates['App\\Services\\DataTableService'] ?? $container->load('getDataTableServiceService')), ($container->privates['App\\Repository\\TrackRepository'] ?? $container->load('getTrackRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\TrackController', $container));

        return $instance;
    }
}
