<?php

namespace Container6x6jTjg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnitTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UnitType' shared autowired service.
     *
     * @return \App\Form\UnitType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UnitType.php';

        return $container->privates['App\\Form\\UnitType'] = new \App\Form\UnitType();
    }
}
